"""
app/schemas/detection.py
========================
Pydantic schemas for the Disease Detection API request and response.
"""
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class DetectionResponse(BaseModel):
    """Response schema for POST /api/v1/detect."""

    disease: str = Field(
        ...,
        description="Detected rice disease label",
        examples=["Brown Spot"],
    )
    confidence: float = Field(
        ...,
        description="Prediction confidence score (0.0 - 1.0)",
        ge=0.0,
        le=1.0,
        examples=[0.9734],
    )
    inference_time_ms: float = Field(
        ...,
        description="Time taken for inference in milliseconds",
        examples=[42.5],
    )
    thinking: Optional[str] = Field(
        default=None,
        description="Internal step-by-step reasoning generated by the AI Pathologist",
        examples=["Key visual signs include small, circular brown lesions..."],
    )
    explanation: Optional[str] = Field(
        default=None,
        description="Farmer-friendly explanation of the detected disease",
        examples=["Brown Spot is a fungal disease that primarily affects rice leaves..."],
    )
    recommendation: Optional[str] = Field(
        default=None,
        description="Actionable steps the farmer should take immediately",
        examples=["Ensure balanced nitrogen fertilization and apply appropriate fungicide..."],
    )
    severity: Optional[str] = Field(
        default=None,
        description="Severity classification: low, medium, high, critical, or unknown",
        examples=["medium"],
    )
    metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional model metadata (architecture, input size, etc.)",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "disease": "Brown Spot",
                "confidence": 0.9734,
                "inference_time_ms": 42.5,
                "thinking": "Key visual signs include small, circular brown lesions. Confidence is high (97.3%). Risk of crop reduction is moderate.",
                "explanation": "Brown Spot is a fungal disease that primarily affects rice leaves, reducing grain weight and quality.",
                "recommendation": "Ensure balanced nitrogen fertilization and apply appropriate fungicide if disease severity exceeds threshold.",
                "severity": "medium",
                "metadata": {
                    "model_name": "MobileNetV2",
                    "num_classes": 4,
                    "input_size": [224, 224],
                },
            }
        }
    }
