"""
app/schemas/history.py
=======================
Pydantic schemas for the Detection History API responses.
"""
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field


class HistoryItemResponse(BaseModel):
    """Response schema for a single history item in a list."""

    id: str = Field(..., description="Unique database record ID")
    filename: str = Field(..., description="Original name of the uploaded image file")
    image_path: str = Field(..., description="Path or URL to retrieve the saved leaf image")
    disease: str = Field(..., description="Detected rice disease label")
    confidence: float = Field(..., description="Prediction confidence score (0.0 - 1.0)", ge=0.0, le=1.0)
    inference_time_ms: float = Field(..., description="Inference runtime in milliseconds")
    severity: Optional[str] = Field(None, description="Pathologist severity level")
    created_at: datetime = Field(..., description="Timestamp of when the diagnosis was recorded")

    model_config = {
        "from_attributes": True
    }


class HistoryDetailResponse(HistoryItemResponse):
    """Detailed response schema for a single history item, including LLM analysis."""

    thinking: Optional[str] = Field(None, description="Step-by-step reasoning generated by the AI Pathologist")
    explanation: Optional[str] = Field(None, description="Farmer-friendly description of the disease")
    recommendation: Optional[str] = Field(None, description="Actionable immediate treatment steps")

    model_config = {
        "from_attributes": True
    }


class HistoryListResponse(BaseModel):
    """Paginated list response schema for history items."""

    items: List[HistoryItemResponse] = Field(..., description="List of history entries for the current page")
    total: int = Field(..., description="Total number of records in the database")
    page: int = Field(..., description="Current page number (1-indexed)")
    size: int = Field(..., description="Number of items per page")
